package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"os"

	"github.com/midbel/sweet/internal/lang/ast"
	"github.com/midbel/sweet/internal/lang/parser"
)

var errConfig = errors.New("invalid configuration file given")

const sweetHelp = `sweet manipulates sql query

sub commands:

* format
* lint
* parse
* scan
* debug

usage: sweet <command> <args>`

func main() {
	flag.Usage = func() {
		fmt.Println(sweetHelp)
		os.Exit(2)
	}
	flag.Parse()

	commands := map[string]func([]string) error{
		"scan":       runScan,
		"parse":      runParse,
		"format":     runFormat,
		"fmt":        runFormat,
		"lint":       runLint,
		"check":      runLint,
		"verify":     runLint,
		"debug":      runDebug,
		"ast":        runDebug,
		"cyclo":      runCyclo,
		"complexity": runCyclo,
	}

	cmd, ok := commands[flag.Arg(0)]
	if !ok {
		fmt.Fprintf(os.Stderr, "unknown command %s", flag.Arg(0))
		fmt.Fprintln(os.Stderr)
		os.Exit(2)
	}
	args := flag.Args()
	if err := cmd(args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

const cycloHelp = ``

func runCyclo(args []string) error {
	return fmt.Errorf("cyclo not yet implemented")
}

const debugHelp = `debug print the AST generated by the parser

usage: debug <sql>`

func runDebug(args []string) error {
	set := createFlag("debug", debugHelp)
	if err := set.Parse(args); err != nil {
		return err
	}
	for _, f := range set.Args() {
		if err := printTree(f); err != nil {
			return err
		}
	}
	return nil
}

func printTree(file string) error {
	r, err := os.Open(file)
	if err != nil {
		return err
	}
	defer r.Close()

	p, err := parser.NewParser(r)
	if err != nil {
		return err
	}
	for {
		stmt, err := p.Parse()
		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			}
			return err
		}
		ast.Debug(os.Stdout, stmt)
	}
	return nil
}
